export const ICONS = {
  MyNotes: "myNotes",
  BMI: "BMI",
  User: "user",
  ExpenseTracker: "expenseTracker",
  Cart: "cart",
  CURD: "curd",
  Calculator: "calculator",
  Weather: "weather",
  Search: "search",
  Brush: "brush",
  Cross: "cross",
  Delete: "delete",
  Edit: "edit",
  Exclamation: "exclamation",
};
